/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author isaac
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainDashBoar
     */
    public MainPage() {
        initComponents();
                this.setResizable(false);
        this.setLocationRelativeTo(null);
//        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
//        this.addWindowListener(new java.awt.event.WindowAdapter() {
//            @Override
//            public void windowClosing(java.awt.event.WindowEvent e) {
//                int selectedOption = JOptionPane.showOptionDialog(null, "¿Desea guardar los datos?",
//                         "Guardar los datos en la base de datos" ,
//                         JOptionPane.YES_NO_OPTION,
//                         JOptionPane.QUESTION_MESSAGE,
//                         null,
//                         new Object[] { "Sí", "No"},
//                         "No");
//                if (selectedOption == JOptionPane.YES_OPTION) {
////                    FunctionsTXT.save();
//                }
//                e.getWindow().dispose();
//                System.exit(0);
//            }
//        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        mainDashBoard1 = new interfaces.MainDashBoard();
        RMDashBoard1 = new interfaces.RMDashBoard();
        TLOUDashBoard1 = new interfaces.TLOUDashBoard();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.addTab("DashBoard", mainDashBoard1);
        jTabbedPane1.addTab("R&M Studio", RMDashBoard1);
        jTabbedPane1.addTab("TLOU Studio", TLOUDashBoard1);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private interfaces.RMDashBoard RMDashBoard1;
    private interfaces.TLOUDashBoard TLOUDashBoard1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private interfaces.MainDashBoard mainDashBoard1;
    // End of variables declaration//GEN-END:variables

    public MainDashBoard getMainDashBoard1() {
        return mainDashBoard1;
    }

    public RMDashBoard getRMDashBoard1() {
        return RMDashBoard1;
    }
    
    public TLOUDashBoard getTLOUDashBoard(){
        return TLOUDashBoard1;
    }
            
}
